### PR TITLE
Given ability to limit stack and program counter 

### PR DESCRIPTION
**Pull request by ssjrnath**
- Stack limit can be set by passing the value to machine constructor as the first argument or setting its default value as 128.

- Program counter limit can be set by passing the value to machine constructor as the first argument or setting its default value as 1000.

### CODE REVIEW

**Review by mrveera — APPROVED** [review]

**Review by mrveera — APPROVED** [review]

**Review by craftybones — CHANGES_REQUESTED** [review]
The current implementation of the programCounter's limit will halt if the program is longer than a thousand lines.

This is not the expectation. The expectation is that the program counter will not *execute* a thousand lines.

For example, the following program should fail after executing a thousand lines

```
10 JMP 10
```

This feature is expected to pre-empt infinite loops. Currently it limits the size of the program

**Review by craftybones — CHANGES_REQUESTED** [review]
This is incorrect. The responsibility of figuring out how many lines have been executed is solely the Program Counter's. 

Also, why break encapsulation on line? A better thing to do is to simply have the check on the program counter's update method. 

Encapsulate the counting in program counter. 

```
// ProgramCounter's constructor
this._linesExecuted = 0;

// ProgramCounter's update method

if(this._linesExecuted > this._limit) throw new Exception(); // the appropriate exception of course.
```

This will throw the exception. There is no need to break line's encapsulation. When the exception is thrown, the execution at the top level automatically injects the right instruction and line number.

**Comment by ssjrnath** [comment]
But program counter doesn't know how many lines executed. 
It points to the address(in our case it is the line number) of the current instruction.

That is the reason I have added that functionality in lines

**Comment by craftybones** [comment]
Lines is a very loose abstraction primarily focused on the collection. Program Counter doesn't know how many lines executed, but it can keep track of how many times it was asked to update itself which is really what we are after. 

Also, doing it this way, causes very few changes to anything else. It is highly localised and doesn't change code elsewhere.

**Review by luciferankon — APPROVED** [review]

**Pull request closed without merging**
